FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY streamlit_requirements.txt .
RUN pip install --no-cache-dir -r streamlit_requirements.txt

# Copy app and model
COPY streamlit_app.py .
COPY actual_predictions_error.csv .

# Expose FastAPI port
EXPOSE 8501

# Command to run FastAPI with uvicorn
CMD ["streamlit", "run", "streamlit_app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]